#!/usr/bin/env python3
"""
Daily morning digest of alt_signals.

Reads the past 24h of alt_signals, groups by source and quality, writes a
markdown brief to ~/.openclaw/workspace/memory/{YYYY-MM-DD}-alt-signals.md,
and (optionally) posts the same content to the morning-brief Discord channel.

Designed to run via systemd timer at ~6:30am ET (12:30 UTC).
"""
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
from __future__ import annotations

import json
import sys
import urllib.request
from datetime import datetime, timezone, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _lib

SOURCE = "morning_digest"

MEMORY_DIR = Path("/home/itsju/.openclaw/workspace/memory")
MORNING_WEBHOOK_FILE = Path("/home/itsju/.openclaw/secrets/discord_morning_brief_webhook")

# How a source name shows up in the brief
SOURCE_LABELS = {
    "sec_8k": "📄 SEC 8-K filings",
    "finra_short_interest": "🩻 Short interest",
    "cme_cot": "📊 CFTC COT",
    "vix_term_structure": "🌪 VIX regime",
    "dix_gex": "🌑 Dark-pool / gamma",
    "ainvest_prompts": "🌐 AInvest crowd",
    "wsb_scan": "🦍 WSB chatter",
    "hn_algo": "🛠 HN + r/algotrading",
}

# Min score per source for inclusion in the brief
SOURCE_MIN_SCORE = {
    "hn_algo": 0,           # idea feed — show all
    "ainvest_prompts": 0,
    "wsb_scan": 60,
    "default": 60,
}

# Max items per source in the brief
SOURCE_LIMIT = {
    "sec_8k": 8,
    "finra_short_interest": 10,
    "cme_cot": 6,
    "vix_term_structure": 2,
    "dix_gex": 3,
    "ainvest_prompts": 6,
    "wsb_scan": 8,
    "hn_algo": 10,
}


def fetch_recent(hours: int = 24) -> dict[str, list[dict]]:
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat(timespec="seconds")
    with _lib.get_db() as conn:
        rows = conn.execute("""
            SELECT id, ts, source, symbol, headline, url, quality_score
            FROM alt_signals
            WHERE ts >= ?
            ORDER BY quality_score DESC, ts DESC
        """, (cutoff,)).fetchall()
    grouped: dict[str, list[dict]] = {}
    for r in rows:
        src = r[2]
        min_score = SOURCE_MIN_SCORE.get(src, SOURCE_MIN_SCORE["default"])
        if r[6] < min_score:
            continue
        grouped.setdefault(src, []).append({
            "id": r[0], "ts": r[1], "source": src, "symbol": r[3],
            "headline": r[4], "url": r[5], "quality_score": r[6],
        })
    return grouped


def render_markdown(grouped: dict[str, list[dict]]) -> tuple[str, int]:
    today = datetime.now(timezone.utc).date()
    total = sum(min(len(v), SOURCE_LIMIT.get(k, 5)) for k, v in grouped.items())

    lines = []
    lines.append(f"# Alt-Signals Morning Digest — {today.isoformat()}")
    lines.append("")
    lines.append(f"_{total} signals across {len(grouped)} sources, past 24h._")
    lines.append("")
    if not grouped:
        lines.append("_No qualifying signals in the last 24 hours._")
        return "\n".join(lines), 0

    # Order sections by total weight in source
    order = sorted(grouped.keys(), key=lambda k: sum(s["quality_score"] for s in grouped[k]), reverse=True)
    for src in order:
        items = grouped[src][: SOURCE_LIMIT.get(src, 5)]
        if not items:
            continue
        label = SOURCE_LABELS.get(src, src)
        lines.append(f"## {label} ({len(items)})")
        lines.append("")
        for s in items:
            sym = f"`{s['symbol']}` " if s["symbol"] else ""
            score_tag = f"_({s['quality_score']:.0f})_"
            url_tag = f" — [link]({s['url']})" if s["url"] else ""
            lines.append(f"- {sym}{s['headline']} {score_tag}{url_tag}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by `~/scripts/alt-signals/morning_digest.py`. Add `?source=X` to flow.db queries for source-specific views._")
    return "\n".join(lines), total


def post_to_morning_brief(markdown: str) -> bool:
    if not MORNING_WEBHOOK_FILE.exists():
        return False
    url = MORNING_WEBHOOK_FILE.read_text().strip()
    # Discord chunks at 2000 chars; split on blank lines
    chunks: list[str] = []
    current: list[str] = []
    size = 0
    for line in markdown.split("\n"):
        if size + len(line) + 1 > 1900 and current:
            chunks.append("\n".join(current))
            current, size = [], 0
        current.append(line)
        size += len(line) + 1
    if current:
        chunks.append("\n".join(current))

    sent = True
    for chunk in chunks:
        payload = json.dumps({"content": chunk}).encode("utf-8")
        req = urllib.request.Request(
            url, data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                if resp.status not in (200, 204):
                    sent = False
        except Exception as e:
            print(f"[digest] discord chunk failed: {e}", file=sys.stderr)
            sent = False
    return sent


def seed_copilot_thread(markdown: str, total: int) -> str | None:
    """
    Insert a fresh copilot_thread so opening /landing in the morning shows
    AIME-style "I've been working overnight" as the most-recent assistant turn.

    Returns thread_id on success, None on failure.
    """
    import hashlib
    import sqlite3 as _sq
    today = datetime.now(timezone.utc).date().isoformat()
    thread_id = hashlib.sha1(f"overnight|{today}".encode()).hexdigest()[:16]
    user_msg = (
        f"_Overnight digest auto-seed for {today}._ "
        "Brief me on what changed while I slept."
    )
    assistant_msg = (
        "Here's what changed in the alt-signals pipeline overnight. "
        f"({total} qualifying signals across sources.)\n\n"
        + markdown
    )
    messages = [
        {"role": "user", "content": user_msg},
        {"role": "assistant", "content": assistant_msg},
    ]
    try:
        conn = _sq.connect("/home/itsju/flow-data/flow.db", timeout=10)
        try:
            cur = conn.cursor()
            cur.execute("""
                INSERT OR REPLACE INTO copilot_threads
                  (thread_id, title, mode, model_last, msg_count, messages_json, created_at, updated_at)
                VALUES (?, ?, 'copilot', 'overnight-digest', ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """, (thread_id, f"Overnight digest — {today}", len(messages), json.dumps(messages)))
            conn.commit()
        finally:
            conn.close()
        return thread_id
    except Exception as e:
        print(f"[digest] seed_copilot_thread failed: {e}", file=sys.stderr)
        return None


def main() -> int:
    grouped = fetch_recent(hours=24)
    markdown, total = render_markdown(grouped)

    MEMORY_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).date()
    out_path = MEMORY_DIR / f"{today.isoformat()}-alt-signals-morning-brief.md"
    out_path.write_text(markdown)

    posted = post_to_morning_brief(markdown) if total > 0 else False

    # Seed copilot thread so it's the most-recent on page load
    thread_id = seed_copilot_thread(markdown, total)

    # Mark signals as included in brief so we don't duplicate next run
    with _lib.get_db() as conn:
        for items in grouped.values():
            for s in items[: SOURCE_LIMIT.get(s["source"], 5)] if False else items:
                pass  # noop, kept commented for shape clarity
        ids = [s["id"] for items in grouped.values() for s in items]
        if ids:
            placeholders = ",".join("?" * len(ids))
            conn.execute(f"UPDATE alt_signals SET sent_to_brief = 1 WHERE id IN ({placeholders})", ids)
            conn.commit()

    _lib.log_event(SOURCE, "tick", {
        "total": total,
        "sources": len(grouped),
        "file": str(out_path),
        "posted": posted,
        "thread_id": thread_id,
    })
    print(f"[digest] total={total} sources={len(grouped)} file={out_path.name} posted={posted} thread_id={thread_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
