#!/usr/bin/env python3
"""
Silver Platters layout (Step 2 of /silver-platter build plan, 2026-05-11).

Centralizes the 8 logical silver platters Boba reads into one canonical directory
at ~/.openclaw/data/silver_platters/ via symlinks. Existing writers (signal-receiver,
firebase-signal-relay, scanners, bible-log, etc) continue writing to their original
paths unchanged. The symlinks make the read surface predictable for path-scoped
agent rules (Step 3) and for the audit log (Step 4).

Modes:
  setup    (default) Create directories + symlinks + README.md. Idempotent.
  rotate   Snapshot current symlink targets into _archive/<YYYY-Www>/<platter>/
  status   Print the layout and current freshness per platter
"""
import json, os, shutil, sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path("/home/ubuntu/.openclaw/data/silver_platters")
ARCHIVE = ROOT / "_archive"
ET = timezone(timedelta(hours=-4))

PLATTERS = [
    {
        "id": "pre_cycle_brief_pack",
        "domain": "trading_context",
        "schedule": "Before each Boba cycle (11:00, 13:30, 15:00, 20:00 ET weekday + every 4h crypto)",
        "files": [
            "/home/ubuntu/.openclaw/workspace/directives/market_briefing.json",
            "/home/ubuntu/.openclaw/workspace/directives/grok_brief.json",
            "/home/ubuntu/.openclaw/workspace/directives/kronos_forecast.json",
            "/home/ubuntu/.openclaw/workspace/directives/market_regime_BTC.json",
        ],
    },
    {
        "id": "scored_signals_shortlist",
        "domain": "signals",
        "schedule": "Continuous, deduped per cycle",
        "files": [
            "/home/ubuntu/mission-control/signal-receiver/data/scored_signals_recent.json",
            "/home/ubuntu/.openclaw/data/multi-day-repeaters.json",
            "/home/ubuntu/.openclaw/workspace/state/boba_seen_signals.json",
        ],
    },
    {
        "id": "best_options_ladder",
        "domain": "execution",
        "schedule": "Daily snapshot at 23:45 ET",
        "files": ["/home/ubuntu/.openclaw/data/best-options"],
    },
    {
        "id": "scanner_aggregate",
        "domain": "signals",
        "schedule": "Every 5min during market hours weekdays",
        "files": ["/home/ubuntu/.openclaw/data/scanners"],
    },
    {
        "id": "boba_daily_picks_log",
        "domain": "execution",
        "schedule": "Per cycle, append-only",
        "files": [
            "/home/ubuntu/.openclaw/workspace/state/boba_daily_picks.json",
            "/home/ubuntu/.openclaw/workspace/state/crypto_boba_daily.json",
        ],
    },
    {
        "id": "post_trade_outcomes",
        "domain": "feedback",
        "schedule": "Per fill + per close",
        "files": ["/home/ubuntu/.openclaw/data/contract-outcomes"],
    },
    {
        "id": "agent_task_queue",
        "domain": "ops",
        "schedule": "Real-time queue",
        "files": ["/home/ubuntu/.openclaw/data/agent-tasks.json"],
    },
    {
        "id": "bible_v3_memory",
        "domain": "memory",
        "schedule": "Append-only on every code-shipping change",
        "files": ["/home/ubuntu/.openclaw/data/bible_v3"],
    },
]


def ensure_symlink(src: Path, dst: Path) -> str:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.is_symlink():
        try:
            current = Path(os.readlink(dst))
        except OSError:
            current = None
        if current == src:
            return "noop"
        dst.unlink()
    elif dst.exists():
        return "skipped (existing non-symlink)"
    dst.symlink_to(src)
    return "linked"


def write_readme():
    et_now = datetime.now(timezone.utc).astimezone(ET).strftime("%Y-%m-%d %H:%M ET")
    lines = [
        "# Silver Platters\n",
        f"\n_Generated by silver_platters_layout.py setup, last updated {et_now}_\n",
        "\n",
        "Single canonical read surface for the 8 logical silver platters Boba reads.\n",
        "Each subdirectory contains symlinks to the live source files. Existing writers\n",
        "(signal-receiver, firebase-signal-relay, scanners, bible-log, etc) keep writing\n",
        "to their original paths unchanged. Editing files inside this directory edits the\n",
        "originals; treat the silver_platters/ tree as a read surface and write through\n",
        "the original tools.\n",
        "\n",
        "## Why this exists\n",
        "Step 2 of the silver-platter build plan (2026-05-11). Before this, Boba's prep\n",
        "files were scattered across ~/.openclaw/data/, ~/.openclaw/workspace/state/,\n",
        "~/.openclaw/workspace/directives/, and ~/mission-control/signal-receiver/data/.\n",
        "Centralizing makes Boba's prompt reproducible, supports path-scoped agent rules\n",
        "(Step 3), and gives the audit log (Step 4) one tree to watch.\n",
        "\n",
        "## Layout\n",
    ]
    for p in PLATTERS:
        lines.append(f"\n### `{p['id']}/` (domain: {p['domain']})\n")
        lines.append(f"_{p['schedule']}_\n\n")
        for f in p["files"]:
            lines.append(f"- `{Path(f).name}` -> `{f}`\n")
    lines.append("\n## Archive\n\n")
    lines.append("`_archive/<YYYY-Www>/<platter>/` snapshots are written by\n")
    lines.append("`silver_platters_layout.py rotate`, scheduled Sun 23:55 ET via cron.\n")
    lines.append("Each snapshot is a deep copy taken at the time of rotation; live writers\n")
    lines.append("are unaffected.\n")
    (ROOT / "README.md").write_text("".join(lines))


def cmd_setup():
    ROOT.mkdir(parents=True, exist_ok=True)
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    actions = []
    for platter in PLATTERS:
        pdir = ROOT / platter["id"]
        pdir.mkdir(parents=True, exist_ok=True)
        for src_path in platter["files"]:
            src = Path(src_path)
            dst = pdir / src.name
            try:
                action = ensure_symlink(src, dst)
            except Exception as e:
                action = f"error: {type(e).__name__}: {e}"
            actions.append((platter["id"], src.name, action))
    write_readme()
    for pid, name, action in actions:
        print(f"  {pid:30s} {name:35s} {action}")
    print(f"\nWrote {ROOT}/README.md")


def iso_week():
    et_now = datetime.now(timezone.utc).astimezone(ET)
    iso = et_now.isocalendar()
    return f"{iso[0]}-W{iso[1]:02d}"


def cmd_rotate():
    week = iso_week()
    target = ARCHIVE / week
    target.mkdir(parents=True, exist_ok=True)
    actions = []
    for platter in PLATTERS:
        snapshot_dir = target / platter["id"]
        snapshot_dir.mkdir(parents=True, exist_ok=True)
        for src_path in platter["files"]:
            src = Path(src_path)
            if not src.exists():
                actions.append((platter["id"], src.name, "missing, skipped"))
                continue
            dst = snapshot_dir / src.name
            try:
                if src.is_dir():
                    if dst.exists():
                        shutil.rmtree(dst)
                    shutil.copytree(src, dst, symlinks=False)
                else:
                    shutil.copy2(src, dst)
                actions.append((platter["id"], src.name, "snapshot ok"))
            except Exception as e:
                actions.append((platter["id"], src.name, f"error: {type(e).__name__}: {e}"))
    print(f"Rotation snapshot at {target}")
    for pid, name, action in actions:
        print(f"  {pid:30s} {name:35s} {action}")


def cmd_status():
    now_ts = datetime.now(timezone.utc).timestamp()
    for platter in PLATTERS:
        pdir = ROOT / platter["id"]
        print(f"\n{platter['id']} ({platter['domain']})")
        if not pdir.exists():
            print("  (not yet set up, run: silver_platters_layout.py setup)")
            continue
        for src_path in platter["files"]:
            src = Path(src_path)
            label = src.name
            if not src.exists():
                print(f"  {label:35s} MISSING")
                continue
            if src.is_dir():
                children = list(src.glob("*"))
                latest = max((c.stat().st_mtime for c in children), default=0)
                age_min = (now_ts - latest) / 60.0 if latest else None
                print(f"  {label:35s} dir, {len(children)} files, newest {age_min:.1f}min" if age_min else f"  {label:35s} dir, empty")
            else:
                age_min = (now_ts - src.stat().st_mtime) / 60.0
                print(f"  {label:35s} file, {src.stat().st_size} bytes, age {age_min:.1f}min")


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "setup"
    if cmd == "setup":
        cmd_setup()
    elif cmd == "rotate":
        cmd_rotate()
    elif cmd == "status":
        cmd_status()
    else:
        print(f"Unknown command: {cmd}. Valid: setup | rotate | status")
        sys.exit(1)


if __name__ == "__main__":
    main()
