package w0;

/* JADX INFO: loaded from: classes.dex */
public abstract class k {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final C1273b f10707a;

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final C1273b f10708b;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    public static final C1273b f10709c;

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final C1273b f10710d;

    static {
        new C1273b("VISUAL_STATE_CALLBACK", 0, "VISUAL_STATE_CALLBACK");
        new C1273b("OFF_SCREEN_PRERASTER", 0, "OFF_SCREEN_PRERASTER");
        new C1273b("SAFE_BROWSING_ENABLE", 3, "SAFE_BROWSING_ENABLE");
        new C1273b("DISABLED_ACTION_MODE_MENU_ITEMS", 1, "DISABLED_ACTION_MODE_MENU_ITEMS");
        new C1273b("START_SAFE_BROWSING", 4, "START_SAFE_BROWSING");
        new C1273b("SAFE_BROWSING_WHITELIST", 4, "SAFE_BROWSING_WHITELIST");
        new C1273b("SAFE_BROWSING_WHITELIST", 4, "SAFE_BROWSING_ALLOWLIST");
        new C1273b("SAFE_BROWSING_ALLOWLIST", 4, "SAFE_BROWSING_WHITELIST");
        new C1273b("SAFE_BROWSING_ALLOWLIST", 4, "SAFE_BROWSING_ALLOWLIST");
        new C1273b("SAFE_BROWSING_PRIVACY_POLICY_URL", 4, "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new C1273b("SERVICE_WORKER_BASIC_USAGE", 1, "SERVICE_WORKER_BASIC_USAGE");
        new C1273b("SERVICE_WORKER_CACHE_MODE", 1, "SERVICE_WORKER_CACHE_MODE");
        new C1273b("SERVICE_WORKER_CONTENT_ACCESS", 1, "SERVICE_WORKER_CONTENT_ACCESS");
        new C1273b("SERVICE_WORKER_FILE_ACCESS", 1, "SERVICE_WORKER_FILE_ACCESS");
        new C1273b("SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new C1273b("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new C1273b("RECEIVE_WEB_RESOURCE_ERROR", 0, "RECEIVE_WEB_RESOURCE_ERROR");
        new C1273b("RECEIVE_HTTP_ERROR", 0, "RECEIVE_HTTP_ERROR");
        new C1273b("SHOULD_OVERRIDE_WITH_REDIRECTS", 1, "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new C1273b("SAFE_BROWSING_HIT", 4, "SAFE_BROWSING_HIT");
        new C1273b("WEB_RESOURCE_REQUEST_IS_REDIRECT", 1, "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        f10707a = new C1273b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        f10708b = new C1273b("WEB_RESOURCE_ERROR_GET_CODE", 0, "WEB_RESOURCE_ERROR_GET_CODE");
        new C1273b("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new C1273b("SAFE_BROWSING_RESPONSE_PROCEED", 4, "SAFE_BROWSING_RESPONSE_PROCEED");
        new C1273b("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new C1273b("WEB_MESSAGE_PORT_POST_MESSAGE", 0, "WEB_MESSAGE_PORT_POST_MESSAGE");
        new C1273b("WEB_MESSAGE_PORT_CLOSE", 0, "WEB_MESSAGE_PORT_CLOSE");
        new C1273b("WEB_MESSAGE_ARRAY_BUFFER", 2, "WEB_MESSAGE_ARRAY_BUFFER");
        new C1273b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new C1273b("CREATE_WEB_MESSAGE_CHANNEL", 0, "CREATE_WEB_MESSAGE_CHANNEL");
        new C1273b("POST_WEB_MESSAGE", 0, "POST_WEB_MESSAGE");
        new C1273b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new C1273b("GET_WEB_VIEW_CLIENT", 3, "GET_WEB_VIEW_CLIENT");
        new C1273b("GET_WEB_CHROME_CLIENT", 3, "GET_WEB_CHROME_CLIENT");
        new C1273b("GET_WEB_VIEW_RENDERER", 6, "GET_WEB_VIEW_RENDERER");
        new C1273b("WEB_VIEW_RENDERER_TERMINATE", 6, "WEB_VIEW_RENDERER_TERMINATE");
        new C1273b("TRACING_CONTROLLER_BASIC_USAGE", 5, "TRACING_CONTROLLER_BASIC_USAGE");
        new f();
        new f();
        new f();
        new C1273b("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new i();
        new C1273b("PROXY_OVERRIDE", 2, "PROXY_OVERRIDE:3");
        f10709c = new C1273b("MULTI_PROCESS", 2, "MULTI_PROCESS_QUERY");
        new C1273b("FORCE_DARK", 6, "FORCE_DARK");
        new C1273b("FORCE_DARK_STRATEGY", 2, "FORCE_DARK_BEHAVIOR");
        new C1273b("WEB_MESSAGE_LISTENER", 2, "WEB_MESSAGE_LISTENER");
        new C1273b("DOCUMENT_START_SCRIPT", 2, "DOCUMENT_START_SCRIPT:1");
        new C1273b("PROXY_OVERRIDE_REVERSE_BYPASS", 2, "PROXY_OVERRIDE_REVERSE_BYPASS");
        new C1273b("GET_VARIATIONS_HEADER", 2, "GET_VARIATIONS_HEADER");
        new C1273b("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new C1273b("GET_COOKIE_INFO", 2, "GET_COOKIE_INFO");
        new C1273b("REQUESTED_WITH_HEADER_ALLOW_LIST", 2, "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new C1273b("USER_AGENT_METADATA", 2, "USER_AGENT_METADATA");
        new j("MULTI_PROFILE", 0, "MULTI_PROFILE");
        new C1273b("ATTRIBUTION_REGISTRATION_BEHAVIOR", 2, "ATTRIBUTION_BEHAVIOR");
        new C1273b("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", 2, "WEBVIEW_INTEGRITY_API_STATUS");
        new C1273b("MUTE_AUDIO", 2, "MUTE_AUDIO");
        new C1273b("WEB_AUTHENTICATION", 2, "WEB_AUTHENTICATION");
        new C1273b("SPECULATIVE_LOADING_STATUS", 2, "SPECULATIVE_LOADING");
        new C1273b("BACK_FORWARD_CACHE", 2, "BACK_FORWARD_CACHE");
        new C1273b("DELETE_BROWSING_DATA", 2, "WEB_STORAGE_DELETE_BROWSING_DATA");
        new j("PREFETCH_URL_V4", 1, "PREFETCH_URL_V4");
        new C1273b("IMPLEMENTATION_ONLY_FEATURE", 2, "ASYNC_WEBVIEW_STARTUP");
        new C1273b("DEFAULT_TRAFFICSTATS_TAGGING", 2, "DEFAULT_TRAFFICSTATS_TAGGING");
        new C1273b("PRERENDER_URL_V2", 2, "PRERENDER_URL_V2");
        new C1273b("SPECULATIVE_LOADING_CONFIG_V2", 2, "SPECULATIVE_LOADING_CONFIG_V2");
        new C1273b("SAVE_STATE", 2, "SAVE_STATE");
        new C1273b("WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", 2, "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE");
        new C1273b("CACHE_PROVIDER", 2, "PROVIDER_WEAKLY_REF_WEBVIEW");
        f10710d = new C1273b("PAYMENT_REQUEST", 2, "PAYMENT_REQUEST");
        new C1273b("WEBVIEW_BUILDER", 2, "WEBVIEW_BUILDER");
    }
}
