package E3;

import W2.n;

/* JADX INFO: loaded from: classes3.dex */
public interface a {

    /* JADX INFO: renamed from: E3.a$a, reason: collision with other inner class name */
    public static final class C0017a {
        public static Object[] a(a aVar, int i4) {
            throw new n("Generated by Android Extensions automatically");
        }
    }
}
