package j7;

import o5.C2488p;

/* JADX INFO: loaded from: classes2.dex */
public interface a {

    /* JADX INFO: renamed from: j7.a$a, reason: collision with other inner class name */
    public static final class C0336a {
        public static Object[] a(a aVar, int i8) {
            throw new C2488p("Generated by Android Extensions automatically");
        }
    }
}
