#!/usr/bin/env python3
"""
Brief Saver — reads market_briefing.md + portfolio data, saves timestamped briefs.
Runs via cron at specific times. Pass brief type as argument.
Usage: python3 brief_saver.py premarket|morning|midday|eod|nightly
"""
import sys, json, os, requests
from datetime import datetime
from pathlib import Path

MEMORY_DIR = Path.home() / ".openclaw" / "workspace" / "memory"
DIRECTIVES = Path.home() / ".openclaw" / "workspace" / "directives"
SECRETS = Path.home() / ".openclaw" / "secrets"

def get_secret(name):
    p = SECRETS / name
    return p.read_text().strip() if p.exists() else None

WEBHOOK = get_secret("discord_briefing_webhook") or get_secret("discord_tv_signals_webhook")

def get_market_briefing():
    p = DIRECTIVES / "market_briefing.md"
    return p.read_text().strip() if p.exists() else "No market briefing available"

def get_portfolio():
    try:
        r = requests.get("http://localhost:3033/api/portfolio", timeout=10)
        if r.ok:
            d = r.json()
            eq = d.get("equity", "?")
            ret = d.get("totalReturn", "?")
            positions = d.get("positions", [])
            lines = [f"Equity: ${eq}", f"Return: {ret}%"]
            for p in positions[:5]:
                sym = p.get("symbol", "?")
                qty = p.get("qty", 0)
                pnl = p.get("unrealized_pl", 0)
                lines.append(f"  {sym}: {qty} shares, P/L: ${pnl:.2f}")
            return "\n".join(lines)
    except: pass
    return "Portfolio data unavailable"

def get_previous_brief(brief_type):
    """Try to read the most recent brief of any type from today"""
    today = datetime.now().strftime("%Y-%m-%d")
    for bt in ["premarket", "morning-brief", "midday", "eod-summary", "nightly"]:
        p = MEMORY_DIR / f"{today}-{bt}.md"
        if p.exists():
            return f"[Previous {bt}]\n{p.read_text().strip()[:500]}"
    # Try yesterday
    from datetime import timedelta
    yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
    for bt in ["eod-summary", "nightly"]:
        p = MEMORY_DIR / f"{yesterday}-{bt}.md"
        if p.exists():
            return f"[Yesterday {bt}]\n{p.read_text().strip()[:500]}"
    return "No previous brief found"

def generate_brief(brief_type):
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%I:%M %p EST")
    
    market = get_market_briefing()
    portfolio = get_portfolio()
    prev = get_previous_brief(brief_type)
    
    # Build the brief content
    type_labels = {
        "premarket": "PREMARKET BRIEF",
        "morning": "MORNING BRIEF", 
        "midday": "MIDDAY CHECK",
        "eod": "EOD SUMMARY",
        "nightly": "NIGHTLY BRIEF"
    }
    
    label = type_labels.get(brief_type, brief_type.upper())
    
    content = f"""# {label} — {now.strftime('%A, %B %d, %Y')} {time_str}

## Portfolio
{portfolio}

## Market Data
{market}

## Previous Brief Reference
{prev}

---
Generated by brief_saver.py at {now.isoformat()}
"""
    
    # Save to file
    file_map = {
        "premarket": f"{date_str}-premarket.md",
        "morning": f"{date_str}-morning-brief.md",
        "midday": f"{date_str}-midday.md",
        "eod": f"{date_str}-eod-summary.md",
        "nightly": f"{date_str}-nightly.md"
    }
    
    filename = file_map.get(brief_type, f"{date_str}-{brief_type}.md")
    filepath = MEMORY_DIR / filename
    MEMORY_DIR.mkdir(parents=True, exist_ok=True)
    filepath.write_text(content)
    print(f"[brief-saver] Saved {filepath} ({len(content)} bytes)")
    
    # Post to Discord
    if WEBHOOK:
        try:
            # Truncate for Discord 2000 char limit
            disc_content = f"**{label}** — {time_str}\n\n{content[:1800]}"
            requests.post(WEBHOOK, json={"username": "JazzyHazzy Brief", "content": disc_content}, timeout=10)
            print(f"[brief-saver] Posted to Discord")
        except Exception as e:
            print(f"[brief-saver] Discord error: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 brief_saver.py premarket|morning|midday|eod|nightly")
        sys.exit(1)
    brief_type = sys.argv[1]
    generate_brief(brief_type)
