package m6;

import E5.n;

/* JADX INFO: loaded from: classes2.dex */
public interface a {

    /* JADX INFO: renamed from: m6.a$a, reason: collision with other inner class name */
    public static final class C0311a {
        public static Object[] a(a aVar, int i7) {
            throw new n("Generated by Android Extensions automatically");
        }
    }
}
