package i9;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-f7c0ba7912e30bee969b60fc55dfe505a38d9b7b2320734346e2a4068d44c6f7 */
/* JADX INFO: loaded from: classes.dex */
public abstract class f {
    public static List a(String str) {
        int length = str.length();
        boolean z10 = false;
        n9.b.d(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            if (str.charAt(0) == 1 && str.charAt(1) == 1) {
                z10 = true;
            }
            n9.b.d(z10, "Non-empty path \"%s\" had length 2", str);
            return Collections.EMPTY_LIST;
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb2 = new StringBuilder();
        int i10 = 0;
        while (i10 < length) {
            int iIndexOf = str.indexOf(1, i10);
            if (iIndexOf < 0 || iIndexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i11 = iIndexOf + 1;
            char cCharAt = str.charAt(i11);
            if (cCharAt == 1) {
                String strSubstring = str.substring(i10, iIndexOf);
                if (sb2.length() != 0) {
                    sb2.append(strSubstring);
                    strSubstring = sb2.toString();
                    sb2.setLength(0);
                }
                arrayList.add(strSubstring);
            } else if (cCharAt == 16) {
                sb2.append(str.substring(i10, iIndexOf));
                sb2.append((char) 0);
            } else {
                if (cCharAt != 17) {
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                }
                sb2.append(str.substring(i10, i11));
            }
            i10 = iIndexOf + 2;
        }
        return arrayList;
    }

    public static j9.t b(String str) {
        return j9.t.A(a(str));
    }

    public static String c(j9.e eVar) {
        StringBuilder sb2 = new StringBuilder();
        int iU = eVar.u();
        for (int i10 = 0; i10 < iU; i10++) {
            if (sb2.length() > 0) {
                e(sb2);
            }
            d(eVar.o(i10), sb2);
        }
        e(sb2);
        return sb2.toString();
    }

    public static void d(String str, StringBuilder sb2) {
        int length = str.length();
        for (int i10 = 0; i10 < length; i10++) {
            char cCharAt = str.charAt(i10);
            if (cCharAt == 0) {
                sb2.append((char) 1);
                sb2.append((char) 16);
            } else if (cCharAt != 1) {
                sb2.append(cCharAt);
            } else {
                sb2.append((char) 1);
                sb2.append((char) 17);
            }
        }
    }

    public static void e(StringBuilder sb2) {
        sb2.append((char) 1);
        sb2.append((char) 1);
    }

    public static String f(String str) {
        StringBuilder sb2 = new StringBuilder(str);
        int length = sb2.length() - 1;
        char cCharAt = sb2.charAt(length);
        n9.b.d(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb2.setCharAt(length, (char) (cCharAt + 1));
        return sb2.toString();
    }
}
